import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/stats.module.css";
import Sidebar from "./components/Sidebar";
import Charts from "./components/Charts";
import { useState, useEffect, useRef } from "react";
import Loading from "./components/Loading";
import LineChart from "./components/LineChart";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [opacity, setOpacity] = useState(0);

  const myRef = useRef(null);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  });

  useEffect(() => {
    setTimeout(() => {
      setOpacity(1);
    }, 1100);
  });

  if (loading) {
    return <Loading />;
  }

  return (
    <div style={{ opacity: opacity }}>
      <Head>
        <title>Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Charts></Charts>
    </div>
  );
}
